# ---------------------------------------------------------
# Audify Bot - All rights reserved
# ---------------------------------------------------------
# This code is part of the Audify Bot project.
# Unauthorized copying, distribution, or use is prohibited.
# © Graybots™. All rights reserved.
# ---------------------------------------------------------

from ... import *
from config import BOT_USERNAME
from pyrogram import *
from pyrogram.types import *

# Buttons: Add bot and Close
Audify = InlineKeyboardMarkup([
    [InlineKeyboardButton("➕ Add Here", url=f"https://t.me/{BOT_USERNAME}?startgroup=true")],
    [InlineKeyboardButton("❌ Close", callback_data="close")]
])

@app.on_message(filters.command(["gen", "ccgen"], [".", "!", "/"]))
async def gen_cc(client, message):
    if len(message.command) < 2:
        return await message.reply_text(
            "💳 Please provide a BIN to generate CCs.\n\nExample: /gen 414720"
        )

    try:
        await message.delete()
    except:
        pass

    aux = await message.reply("🔄 Generating CCs...")

    bin = message.text.split(None, 1)[1]
    if len(bin) < 6:
        return await aux.edit("⚠️ Please provide a valid BIN with at least 6 digits.")

    try:
        resp = await api.ccgen(bin, 10)
        cards = resp.liveCC

        mention = f"[{message.from_user.first_name}](tg://user?id={message.from_user.id})"

        text = (
            "💳 **Live CCs Generated**\n\n"
            f"`{cards[0]}`\n"
            f"`{cards[1]}`\n"
            f"`{cards[2]}`\n"
            f"`{cards[3]}`\n"
            f"`{cards[4]}`\n"
            f"`{cards[5]}`\n"
            f"`{cards[6]}`\n"
            f"`{cards[7]}`\n"
            f"`{cards[8]}`\n"
            f"`{cards[9]}`\n\n"
            f"👤 Generated by: {mention}"
        )

        await aux.edit(
            text,
            reply_markup=Audify,
            disable_web_page_preview=True,
            parse_mode=None
        )

    except Exception as e:
        await aux.edit(f"❌ Error: {e}")
